### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by Jacob-Dentes** [thalmiclabs/myo-sphero-ios#1]
I have no idea how to run this application. Read the "Read Me" file but did not help. Does anybody know how to run the application.

**Comment by smngreenberg** [comment]
This is an iOS project that will need to be deployed to a compatible phone or tablet using Xcode and a valid iOS developer account. This application will also be published on the iTunes App Store at some point.

**Comment by Dmurph24** [comment]
Do you know when this will be published to the iTunes Store? If it needs some additional polish I would be able to help (I was in the MyoDevMonday blog from last week). I have experience with iOS development and the Myo.

**Comment by smngreenberg** [comment]
The remaining items before submission are all UI-related. Explaining the application, control scheme, etc. Our creative team will be taking a look at it over the next little while. Hopefully after that point it'll be a quick cycle to get it live in the App Store.
